### ISSUE TITLE
Neighborhood poverty links breaking

### ISSUE THREAD

**Issue by mmontesanonyc** [nychealth/EH-dataportal#1049]
[Neighborhood poverty links view](https://a816-dohbesp.nyc.gov/IndicatorPublic/data-explorer/economic-conditions/?id=103#display=links) shows no chart and a page of infinite length.

Looking at the rendered chart spec, we have an empty `data`. 

<img width="1202" alt="image" src="https://github.com/nychealth/EH-dataportal/assets/55593359/2406ddfb-023c-4e40-b977-935110861552">

<img width="486" alt="image" src="https://github.com/nychealth/EH-dataportal/assets/55593359/e350fd47-3b09-4af7-9dad-4d7a5ce1331f">

**Comment by cgettings** [comment]
The issue stems from an overlooked edge case. I'm actually surprised it doesn't break more links charts.

**Just to lay it out:**

Find the GeoTypes that the primary measure and the secondary/linked measure share. Filter each dataset so that they each contain only these GeoTypes. Then, keep only the most recent time period in the primary measure data. Now, keep only the closest time period in the secondary/linked measure data. **_These two datasets might have different GeoTypes._** 

In this case, poverty and bicycle injuries share CD and UHF; the most recent primary data occurs at UHF, but the closest secondary data occurs at CD. Thus, no data, no chart.

My fix is to get the GeoTypes in the most recent primary data and filter the secondary data based on this, instead of the shared geos, and then calculate the closest secondary data. If the most recent primary data contains all shared geos, it should produce the same dataset as before; given this edge case, it will still work.

**UPDATE:** It works 👍

**Comment by mmontesanonyc** [comment]
Wow, nice! That was fast and yeah, I'm surprised that it doesn't affect more links. Thanks!
