### ISSUE TITLE
Suppressed geos not grayed out

### ISSUE THREAD

**Issue by cgettings** [nychealth/EH-dataportal#1084]
Example: Northern Staten Island:

https://a816-dohbesp.nyc.gov/IndicatorPublic/data-explorer/asthma/?id=18#display=map

![image](https://github.com/user-attachments/assets/51ec2a6c-5b99-4943-8ebe-f3fe7770c69c)

**Comment by cgettings** [comment]
I feel like I coded a fix for this last year. It may have gotten lost when adding the bubble maps. 

Issue is (IRRC) the `null` values are converted to numeric, which turns `null` into `0`, which gets the lightest shade.

**Comment by mmontesanonyc** [comment]
Might have to do with issues around the condition, below, which I just turned from Value to DisplayValue... can definitely dig deeper into this (or do some reverting) soon. It's probably a change that got caught up in some other changes I was making last month - sorry about that! 

![image](https://github.com/user-attachments/assets/dacf9b25-9609-469e-979e-cb2cf5fc4dd5)

**Comment by mmontesanonyc** [comment]
Weird behavior all around. 

A few notes:
- using `DisplayValue` as the test shouldn't work, because DisplayValue is a string with numbers and symbols.
- using `isValid(datum.Value)` should work, that's what it was designed around.  [isValid documentation](https://vega.github.io/vega/docs/expressions/#isValid).
- The 'else' case (`"value": "#808080"`) just isn't rendering at all.
- The desired tooltip does appear - when hovering on the stroke. But the fill isn't happening. 

And:
- I've done some digging through previous versions of this spec and can't find one working as expected
- I seem to remember it working as expected - including, changing the suppressed color because I felt it was too dark, darker than the basemap gray.

**Comment by mmontesanonyc** [comment]
Strangely, this works with `"bin": true` but not with `"bin": false`.

![image](https://github.com/user-attachments/assets/297ee695-c52f-432e-ac23-63387f28d7a1)

**Comment by mmontesanonyc** [comment]
So this gets at [changes made from vega@5.29.0 to vega@5.30.0](https://github.com/vega/vega/releases/tag/v5.30.0), which include [changes to null handling](https://github.com/vega/vega/pull/3926).

If we convert [our VL spec](https://vega.github.io/editor/#/gist/9d7427f474805f588de87d770f5344a2/spec.json) to a vega spec and comment out the below, we have the desired state.

![image](https://github.com/user-attachments/assets/bf2fb951-d81e-45d2-8c46-1e5d49f1dc0e)

Works if we limit our use to 5.18.1, for example, but would prefer to have a forward-compatible approach.

**Comment by mmontesanonyc** [comment]
#1088 to address this temporarily.

**Comment by cgettings** [comment]
Adding `"scale": {"invalid": {color: {value: '#808080'}}}` to the top-level `config` solves this without the conditional in `encoding.color`. Works for `vega-lite@5.20.1` and `vega-lite@5.6.1` and probably will continue working in the future.

See: https://github.com/nychealth/EH-dataportal/commit/ca3b34b1e23475f2161ca11d50c207889b5a86c3#diff-0a333fb23ee55c1934466567866bf25e7e78a352a266a0da04fdb8bf1853177eR208
