### ISSUE TITLE
Enhance neighborhood lookup

### ISSUE THREAD

**Issue by cgettings** [nychealth/EH-dataportal#110]
For NR you can lookup using ZIP and UHF 42 name. For AQE you can lookup using NTA name. 

Options, from easier to harder:

- [ ] Browser geolocation
- [ ] Flexible neighborhood name lookup
- [ ] Address lookup

As an example for # 3, “Kew Gardens” matches NTA “QN61” / “Kew Gardens”, but not UHF42 407 / “Southwest Queens”. Already have an idea for how to do it.

**Comment by mmontesanonyc** [comment]
Let's chat through your idea.

The initial implementation of the AQE used an address lookup, which turned out to be clunky and frustrating - users wanted to explore other neighborhoods, too, but it took work for them to figure out a valid address to look up. Address lookup could work in conjunction with a clickable choropleth map, I think, but not alone. 

I think for the text-based ones it's easy to add additional text fields that the entry scans (which we essentially do with the name / ZIP approach for UHFs. 

But not all the units nest (eg ZIPs nest into UHFs so that's easy, but don't share boundaries with NTAs) so that complicates things.

**Comment by cgettings** [comment]
My idea is that we add all of the options, not just 1. So users would be able to look up by ZIP and also address. I realize that might be difficult, so I'm going to edit the list to put address lookup last.

For non-nesting neighborhoods, we'd have to return multiple options. Like if Kew Gardens is part of 2 different UHFs, then we suggest both of them.

**Comment by mmontesanonyc** [comment]
I like that approach. Sounds a little similar to [the CD/UHF tool on the nowportal](https://a816-dohbesp.nyc.gov/IndicatorPublic/CommunityDistrict.aspx). I think the interaction pattern would need some additional thought in order to be smooth and intuitive - but overall the aim of having users be able to put in almost anything and return a useful promp/geography that guides them to a relevant selection - that's a good approach.

**Comment by mmontesanonyc** [comment]
NB, browser geolocator is in effect on `feature-take-action` - basically the [DOITT NYC Core Framework map function](https://www1.nyc.gov/assets/oti/html/nyc-core-framework/maps.html) lets you enter an address and return a ton of information, including CD, ZIP, census tract, etc etc. Tho we'd need a UHF list to match ZIP -> UHF.

**Comment by mmontesanonyc** [comment]
I'm going to close this as inactive right now. It's in the "Data Explorer/Site Enhancements" bit in our project board and document, and I want to keep the Issues list focused on active things.
