### ISSUE TITLE
Refactor NR backend

### ISSUE THREAD

**Issue by cgettings** [nychealth/EH-dataportal#601]
Currently we use a JSON file for each NR type x UHF 42. The code ranges over elements in `report_topic_data`, which have the indicator data "rows" in them for that topic. 

The code should instead range over topics in a YAML file in the root data folder. Topics have names and descriptions, and have indicator IDs nested underneath. The indicator IDs and neighborhood names are used to subset a single data file with all indicators. `indicator_name` and `indicator_description` can be taken from `IndicatorData/indicator_names.json`, or another file derived from `indicators.json`.

The idea to refactor the NRs arose while designing our new database, but the transition to that new database will be easier if we do the refactoring now-ish. In the bargain, we get a simpler NR dataflow sooner.

**Comment by mmontesanonyc** [comment]
Done, but waiting on NR Print Styles to be implemented before finalization.

**Comment by mmontesanonyc** [comment]
With this work, can we also add the data source to the NRs? I forget exactly what this refactoring was accomplishing, and I'm not sure if we have source info in the NR json - but, would be great to add that and find a place in the modal (toward the button?) for it.

**Comment by mmontesanonyc** [comment]
A few notes from conversation:
- NR data flow is last legacy of old site - refactoring can help bring everything into the future
- We can move NR specs to the front-end, to a data file - one for each report topic, with headers and indicator/measure IDs. This will let content managers revise each NR. We'll probably need both indicator ID and measure ID.
- We'll probably need `UHF_ID` in each output's frontmatter, to reference in each report and help filter data
- That should give us the pieces to filter indicator files - since we'll need to get `[indicatorID].json` , filter by UHF42, get the correct measure, get the most recent year, get the citywide, boro, and UHF values.

A few things:
- We have some NR-only indicators that are not in the DE. We'll need them in /indicators even if they're not in the DE.
- In re-working it, we can visualize the UHF / Boro / NYC-value comparison
- May want to reconsider use of trend charts

**Comment by cgettings** [comment]
1. Re: Indicators: It should be easy to include the NR-only files in `/indicators`. They'll only appear in the DE if we add them to the topic markdown frontmatter. 
2. Re: Trend chart: we could use that as one way to visualize UHF / Boro / NYC-value comparison. If we make the lines different colors, then it'll be easy to get the gist. Should be simple to filter the data, since it'll always be the same comparison.

**Comment by mmontesanonyc** [comment]
re: "should be simple to filter the data" - yeah, we can do `if` statements re: the UHF_id, and use that to filter for the correct boro. That was part of the original plan for the NRs that didn't quite get operationalized.

**Comment by mmontesanonyc** [comment]
Completed with Jan 2024 major site change push. #963

**Comment by cgettings** [comment]
# Here's how we solve the NR build / export dilemma:

Create and checkout an `update-` branch in the site repo. Create and checkout a branch with the same name in the data repo. Edit the `NR_content` YAML files in the site repo, then in the data repo run the export scripts to re-export the data. 

The data export scripts will fetch the report topic indicators from the site repo, by default using the update branch name (which has the same name in both repos). So, it'll pick up on the latest changes. (You can use whichever site repo branch you want, but naming them the same thing makes it easier.)

In the data repo, merge the update branch into `production`. This will get the updated data files onto production. Then, do the same thing in the site repo. This will trigger a build, which will use the updated data files thanks to the preceding merge in the data repo.

## Will it break things?

The only changes will be in the NR data export files.  Data from `report/` is only used by Hugo, and data in `viz/` is filtered by the site code. So, if we add an indicator to a topic, nothing breaks. If we remove an indicator, that indicator will break on the prod site until we deploy, when it will totally disappear, so not too much harm done.
