### ISSUE TITLE
Add 'geography' dropdown so that the user can see specified geos rather than just the finest-available.

### ISSUE THREAD

**Issue by cgettings** [nychealth/EH-dataportal#616]

**Comment by cgettings** [comment]
@mmontesanonyc, @sportsmanam On dev. Feel free to try and break.

**Comment by mmontesanonyc** [comment]
Looking good. I even tested on variable NYCKids stuff (Children with asthma) and it correctly changes year-specific NYCKIDS geo on time change. Really good handling of things - if no map, I'm getting good reversion to Summary on indicator change. 

One thing I think this lets us do is consolidate some NTA-level indicators that are "separate indicators" (asthma ED visits, HVI). We could add the NTA-level data to the general indicator, get rid of the "by NTA" indicator. 

Planning to add Boroughs to the dropdown? I think it'd be good.

**Comment by cgettings** [comment]
Yeah, I'll get on that after lunch.

**Comment by cgettings** [comment]
@mmontesanonyc Just added boro. Had to troubleshoot and re-create the boro topojson, but it's all good now.

**Comment by mmontesanonyc** [comment]
I haven't found myself able to break this - if you agree, I think it's ready for primetime. 

One thing that this makes me think about is menu styles. I don't think this is anything that we should work on with this project, but flagging for future consideration and possible work with our contractor/partners. Persisting selection names in the menu headers (eg, so that when you choose CD in geography, then CD is what shows in that dropdown button) would be interesting, and would let us remove some information from the chart title/subtitle. This might require a lot of changes to button styles, and they might need labels that look differently, so I don't want to rush it - but want to consider it.

**Comment by mmontesanonyc** [comment]
Closing. Great work.
