### ISSUE TITLE
Data just halved! What's going on?!

### ISSUE THREAD

**Issue by Atcold** [nychealth/EH-dataportal#752]
The PM2.5 concentration just halved.
What's going on?!?!

This screenshot is from Thu 8 Jun 2023.
![PHOTO-2023-06-08-14-56-54](https://github.com/nychealth/EH-dataportal/assets/2119355/26c960be-af23-47df-a877-b75aef90c237)

This is from Fri 9 Jun 2023.
![image](https://github.com/nychealth/EH-dataportal/assets/2119355/462b7f37-720c-4b77-9c0d-f48119fae292)

**Comment by mmontesanonyc** [comment]
Hi there, thanks for finding our repo, and for asking. 

As that page says, our air quality team applied a calibration algorithm to the data from the realtime air quality monitors. The air quality team was evaluating the calibration when the smoke emergency hit, and rolled out the update as soon as we could. These real-time monitors aren't used to calculate the Air Quality Index - that's informed by the state Department of Environmental Conservation's network of monitors. Our real-time monitors are used to estimate street-level exposures in a select locations. Since we publish the data in near-real-time, they are preliminary and subject to change as we QC the technology.

**Comment by Atcold** [comment]
Thanks for the reply, @mmontesanonyc.

> The air quality team […] rolled out the update as soon as we could

What commit is that?
