### ISSUE TITLE
Improve / enhance data download function

### ISSUE THREAD

**Issue by etorem** [nychealth/EH-dataportal#811]
For these indicators: 
https://a816-dohbesp.nyc.gov/IndicatorPublic/beta/data-explorer/housing-maintenance/?id=45#display=summary
https://a816-dohbesp.nyc.gov/IndicatorPublic/beta/data-explorer/asthma/?id=2380#display=map

Thanks!

**Comment by mmontesanonyc** [comment]
Elaborating a bit...
- From the map display, 'download: current table view' downloads the finest available geography regardless of what's being displayed.
- Curiously, housing maintenance has UHF42 data available in the map (good) but not in the table, so, hard to use table view as a workaround to download those data.

**Comment by mmontesanonyc** [comment]
Semi-related - possibly a new issue. For instances where we're showing NTA, can we also import the standard NTA code? @cgettings, I know you had created another (can you document that in a readme in EHDP/geographies?) because of issues with alphanumeric and the Data Explorer js - wondering if we can still include the alphanumeric so that when somebody downloads, they also get the standard NTA codes.

**Comment by mmontesanonyc** [comment]
Proposed function:
- Download the data that you're seeing right now (this view)
- Download full indicator

+ add `href=""` to get mouseover button, and `this.preventDefault()` ?

I might restructure those footer buttons, too.

**Comment by mmontesanonyc** [comment]
nb, added pointer to data download buttons and did a little thinking/investigating:
- This Table View is for the table, but it appears on the other views, and I think it communicates "download the data you're seeing now" - that's a problem. We should have a "Download the data you're seeing right now" option as the primary option.
- The Table view ("full table") is nicely formatted with the right info - IMO that's what people probably want when they download and that's what we should aim to build.
- But for most of the view functions, we pass in a `data` object. But we can't just send that to the download, because it's missing a ton of information: it doesn't have measure names (just measure IDs), for example. We could build a better download object as a separate function, but it would require some table manipulation (Arquero?) to combine the right information.

**Comment by mmontesanonyc** [comment]
@cgettings and @etorem, could you please do a little bit of stress testing on `hotfix-de-download`? I've rebuilt the download function. There are now two options:
- This view: downloads the data that's currently visible: table, map, trend, links, or disparities. 
- Full table: fairly straightforward, all geographies, measures, and times for the indicator

Mainly, we're shooting to provide data files that have the expected information - ilke the indicator and measure names, and the data that somebody is seeing in the chart on the screen. I've run into some issues this morning with this where  parts of the data download have interfered with other parts of the DE (obvious issues when toggling options, console errors, etc), but I think I've solved that (although the trend/comparisons data file isn't quite as tidy as I'd like). 

If you two could please take a close look at the downloads and make sure they make sense, as well as click around a bundle and let me know if you see anything broken, that would be great! This was a little tricker than I anticipated and I broke some things along the way - and fixed them - but want to make sure that we find any other potential bugs before release.

**Comment by mmontesanonyc** [comment]
Merged and queued for deployment - going to close this issue.
