### ISSUE TITLE
Vertical line for trend charts with "do not compare to previous years" recommendations

### ISSUE THREAD

**Issue by cgettings** [nychealth/EH-dataportal#840]
Add a section in `indicators.json` at the indicator level. Section has:
1. yes/no switch
2. mouseover message for line

No sure where to store this info in the old/new database. Rows in `unreliability`/`data_flag` are associated with data points. This message is associated with a row in `internal_indicator`/`indicator` and two rows in `indicator_year`/`time_period`. Maybe a special-purpose viz table.

**Comment by mmontesanonyc** [comment]
I think the idea of having a mouseover message is pretty cool. Why are those metadata at the indicator level and not the measure level? I could imagine hypotheticals where a custom message would be needed for a specific measure, as opposed to being at all measures of an indicator.

**Comment by mmontesanonyc** [comment]
Got it! Pretty simple...

We have 2 layers on the line chart; the first is the lines, the second includes a pivot transform that powers the tooltip. We can easily add a 3rd based on specification in `metadata.json`. See line 436.

<img width="519" alt="image" src="https://github.com/nychealth/EH-dataportal/assets/55593359/71dcf104-cb9e-43a8-82a7-07835e62f7b3">

Styles can be easily modified - I'm not sure if we want to keep the red or do something a little less attention-grabby, like a `darkgray`. The main other piece of information that needs to get from metadata.json to the spec is the year -  `encoding.x.datum` is the first year that can't be compared to previous years.

```
    {
      "mark": "rule",
      "encoding": {
        "x": {
          "datum": "2019"          
          },
         "xOffset": {"value": 0.5},
        "color": {"value": "red"},
        "size": {"value": 2},
        "strokeDash": {"value": [2, 2]}
      }
    }
```


<img width="691" alt="image" src="https://github.com/nychealth/EH-dataportal/assets/55593359/5f053e95-eb19-4c1a-be2e-63ada45805d7">

Lastly - rather than adding a note on the canvas, can we just use a footnote to the trend chart?

@cgettings

**Comment by mmontesanonyc** [comment]
Notes:
- Export code can check source ID, and add two metadata fields: one 0/1 for the vertical line, and one specifying the year (which means we can use this implementation for other purposes)
- DE javascript can check for line=1, insert that layer, and specify the year. 
- Footnote can be included in data

@cgettings

**Comment by cgettings** [comment]
Last 2 commits, plus matching data repo changes, should finish this

**Comment by mmontesanonyc** [comment]
Took a quick look - nice. So in `metadata.json` I'm seeing `"TrendNoCompare": "2021"` which lets us use `noCompare` for any purpose, as long as we specify the year. 

We likely need to pair this with a footnote in the data, yes?  Let's touch base on it shortly, and plan to run through it with WM, too.

**Comment by cgettings** [comment]
Re: footnote, we can probably just set one in the code for now, and then if we need to, we can get more creative.

**Comment by cgettings** [comment]
Add conditional so that the line only displays if there are time periods later the line

**Comment by mmontesanonyc** [comment]
Completed.
